#!/usr/bin/env node

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const PACKAGE_ROOT = dirname(fileURLToPath(import.meta.url))
const PACKAGE = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'package.json'), 'utf8'))
const BUNDLE = PACKAGE.name
const GENERATED_MARKERS = [
  '# Generated by @zenx0x/allinflash.',
  '# Generated by scripts/install_allinflash_profile.py.',
]

function fail(message, code = 1) {
  process.stderr.write(`allinflash: ${message}\n`)
  process.exit(code)
}

function parseArgs(argv) {
  const command = argv[0] ?? 'help'
  const options = {}
  for (let index = 1; index < argv.length; index += 1) {
    const token = argv[index]
    if (!token.startsWith('--')) fail(`unexpected argument ${token}`)
    const key = token.slice(2)
    if (['dry-run', 'force', 'skip-install', 'skip-runtime-check', 'json'].includes(key)) {
      options[key] = true
      continue
    }
    const value = argv[index + 1]
    if (!value || value.startsWith('--')) fail(`--${key} requires a value`)
    options[key] = value
    index += 1
  }
  return { command, options }
}

function validProfile(value) {
  return /^[a-zA-Z0-9][a-zA-Z0-9-]*$/.test(value)
}

function posixPath(value) {
  return resolve(value).replaceAll('\\', '/')
}

function yamlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`
}

function dshHome(options) {
  return resolve(options['dsh-home'] ?? process.env.DSH_HOME ?? join(homedir(), '.dsh'))
}

function profilePaths(options) {
  const profile = options.profile ?? 'allinflash'
  if (!validProfile(profile)) fail('profile must start alphanumeric and contain only letters, numbers, and hyphens')
  const root = join(dshHome(options), 'profiles', profile)
  return {
    profile,
    root,
    packageJson: join(root, 'package.json'),
    patch: join(root, 'cordis.patch.yml'),
    workspace: join(root, 'pnpm-workspace.yaml'),
  }
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'))
  } catch (error) {
    fail(`cannot read ${path}: ${error.message}`)
  }
}

function commandResult(command, args, env = process.env, { shell = false } = {}) {
  const result = spawnSync(command, args, {
    encoding: 'utf8',
    env,
    shell,
    windowsHide: true,
  })
  return {
    ok: result.status === 0,
    status: result.status,
    stdout: String(result.stdout ?? '').trim(),
    stderr: String(result.stderr ?? result.error?.message ?? '').trim(),
  }
}

function dshResult(args, env = process.env) {
  if (process.platform === 'win32') {
    return commandResult(process.env.ComSpec ?? 'cmd.exe', ['/d', '/s', '/c', 'dsh', ...args], env)
  }
  return commandResult('dsh', args, env)
}

function runtimeConfig(options) {
  const command = options['runtime-command'] ?? 'allinluna'
  const commandArgs = ['--adapter', 'deepseek-harness']
  const config = {
    command,
    commandArgs,
    timeoutMs: Number(options['timeout-ms'] ?? 30000),
    model: options.model ?? 'deepseek-v4-flash',
    subagentProvider: options['subagent-provider'] ?? 'spawn',
  }
  if (!Number.isSafeInteger(config.timeoutMs) || config.timeoutMs <= 0) fail('--timeout-ms must be a positive integer')
  if (options.db) config.db = posixPath(options.db)
  if (options.cwd) config.cwd = posixPath(options.cwd)
  return config
}

function patchYaml(config) {
  const lines = [
    GENERATED_MARKERS[0],
    '# This profile layer owns local runtime values for the All in Flash bundle.',
    '- id: allinflash',
    '  config:',
    `    command: ${yamlString(config.command)}`,
    `    commandArgs: [${config.commandArgs.map(yamlString).join(', ')}]`,
  ]
  if (config.db) lines.push(`    db: ${yamlString(config.db)}`)
  if (config.cwd) lines.push(`    cwd: ${yamlString(config.cwd)}`)
  lines.push(
    `    timeoutMs: ${config.timeoutMs}`,
    `    model: ${yamlString(config.model)}`,
    `    subagentProvider: ${yamlString(config.subagentProvider)}`,
  )
  return `${lines.join('\n')}\n`
}

function profilePackage(existing = {}, dependencySpec = PACKAGE.version) {
  const bundles = existing.dsh?.profile?.bundles ?? ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app']
  const mergedBundles = [...new Set([...bundles, BUNDLE])]
  return {
    ...existing,
    name: existing.name ?? 'dsh-profile-allinflash',
    private: true,
    dependencies: { ...(existing.dependencies ?? {}), [BUNDLE]: dependencySpec },
    dsh: { ...(existing.dsh ?? {}), profile: { ...(existing.dsh?.profile ?? {}), bundles: mergedBundles } },
    allinflash: { managed: true, version: PACKAGE.version },
  }
}

function assertSafeProfile(paths, options) {
  if (!existsSync(paths.root)) return
  const patch = existsSync(paths.patch) ? readFileSync(paths.patch, 'utf8') : ''
  const manifest = existsSync(paths.packageJson) ? readJson(paths.packageJson) : {}
  const managed = manifest.allinflash?.managed === true || GENERATED_MARKERS.some((marker) => patch.startsWith(marker))
  if (!managed && !options.force) {
    fail(`profile ${paths.profile} already exists and is not managed by All in Flash; choose another profile or pass --force`)
  }
}

function installProfile(paths, options) {
  if (options['skip-install']) return { skipped: true }
  const env = { ...process.env, DSH_HOME: dshHome(options) }
  const result = dshResult(['plugin', '--profile', paths.profile, 'install'], env)
  if (!result.ok) fail(`DSH package installation failed: ${result.stderr || result.stdout}`)
  return { skipped: false, output: result.stdout }
}

function checkRuntime(config, options) {
  if (options['skip-runtime-check']) return { skipped: true }
  const result = commandResult(config.command, [...config.commandArgs, '--version'])
  if (!result.ok) {
    fail(`All in Luna CLI is unavailable (${config.command}). Install it with "python -m pip install allinluna" or pass --runtime-command.`)
  }
  return { skipped: false, version: result.stdout }
}

function init(options) {
  const paths = profilePaths(options)
  const config = runtimeConfig(options)
  const dependencySpec = options['package-spec'] ?? PACKAGE.version
  assertSafeProfile(paths, options)
  const runtime = checkRuntime(config, options)
  const existing = existsSync(paths.packageJson) ? readJson(paths.packageJson) : {}
  const files = {
    [paths.packageJson]: `${JSON.stringify(profilePackage(existing, dependencySpec), null, 2)}\n`,
    [paths.patch]: patchYaml(config),
    [paths.workspace]: 'packages:\n  - .\nnodeLinker: hoisted\nautoInstallPeers: false\n',
  }
  if (!options['dry-run']) {
    mkdirSync(paths.root, { recursive: true })
    for (const [path, content] of Object.entries(files)) writeFileSync(path, content, 'utf8')
  }
  const installation = options['dry-run'] ? { skipped: true, reason: 'dry-run' } : installProfile(paths, options)
  return {
    ok: true,
    profile: paths.profile,
    profileDir: paths.root,
    package: `${BUNDLE}@${PACKAGE.version}`,
    runtime,
    installation,
    files: Object.keys(files),
    start: `dsh --profile ${paths.profile}`,
  }
}

function doctor(options) {
  const paths = profilePaths(options)
  const manifest = existsSync(paths.packageJson) ? readJson(paths.packageJson) : null
  const patch = existsSync(paths.patch) ? readFileSync(paths.patch, 'utf8') : ''
  const bundles = manifest?.dsh?.profile?.bundles ?? []
  const dependency = manifest?.dependencies?.[BUNDLE]
  const runtime = commandResult(options['runtime-command'] ?? 'allinluna', ['--adapter', 'deepseek-harness', '--version'])
  const dsh = dshResult(['--version'])
  const checks = {
    profileExists: existsSync(paths.root),
    dependencyDeclared: typeof dependency === 'string',
    dependencyResolved: existsSync(join(paths.root, 'node_modules', '@zenx0x', 'allinflash', 'package.json')),
    bundleEnabled: bundles.includes(BUNDLE),
    patchConfigured: patch.includes('- id: allinflash'),
    runtimeAvailable: runtime.ok,
    dshAvailable: dsh.ok,
  }
  return {
    ok: Object.values(checks).every(Boolean),
    profile: paths.profile,
    profileDir: paths.root,
    checks,
    dependency: dependency ?? null,
    runtime: runtime.stdout || runtime.stderr,
    dsh: dsh.stdout || dsh.stderr,
  }
}

function help() {
  return `All in Flash ${PACKAGE.version}\n\nUsage:\n  allinflash init [--profile allinflash] [--dsh-home PATH] [--force]\n  allinflash doctor [--profile allinflash] [--dsh-home PATH]\n\nInit options:\n  --runtime-command CMD     All in Luna executable (default: allinluna)\n  --package-spec SPEC       npm dependency spec (default: current published version)\n  --db PATH                 Optional durable runtime database\n  --cwd PATH                Optional runtime working directory\n  --model MODEL             DSH model route (default: deepseek-v4-flash)\n  --skip-runtime-check      Generate config without executing allinluna --version\n  --skip-install            Generate config without running dsh plugin install\n  --dry-run                 Print the intended result without writing files\n  --force                   Replace an existing unmanaged profile\n`
}

const { command, options } = parseArgs(process.argv.slice(2))
if (command === 'help' || command === '--help' || command === '-h') {
  process.stdout.write(help())
} else if (command === 'init') {
  process.stdout.write(`${JSON.stringify(init(options), null, 2)}\n`)
} else if (command === 'doctor') {
  const result = doctor(options)
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`)
  if (!result.ok) process.exitCode = 1
} else {
  fail(`unknown command ${command}; use "allinflash help"`)
}
