"""Install an All in Flash DeepSeek Harness profile into a selected DSH home.

The script writes only a new/selected profile directory.  It never alters the
shipped DSH presets or an existing profile without ``--force``.  Run the DSH
package installation afterwards so pnpm resolves the local Cordis package.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "plugins" / "deepseek-harness"


def profile_files(*, profile_dir: Path, allinluna_root: Path) -> dict[Path, str]:
    # ``uv run allinluna`` uses the project environment selected by uv.  This
    # survives a stale checked-in virtualenv and is also the command verified
    # by the repository's development workflow.
    command = "uv"
    command_args = ["run", "allinluna", "--adapter", "deepseek-harness"]
    package = {
        "name": "dsh-profile-allinflash",
        "private": True,
        "dependencies": {"@zenx0x/allinflash": f"file:{PLUGIN.as_posix()}"},
        "dsh": {
            "profile": {
                "bundles": [
                    "@deepseek-ai/dsh-base",
                    "@deepseek-ai/dsh-web-app",
                    "@zenx0x/allinflash",
                ],
            },
        },
    }
    patch = [
        {
            "id": "allinflash",
            "name": "@zenx0x/allinflash",
            "config": {
                "command": command,
                "commandArgs": command_args,
                "db": (allinluna_root / "runtime.db").as_posix(),
                "cwd": allinluna_root.as_posix(),
                "timeoutMs": 30000,
                "model": "deepseek-v4-flash",
                "subagentProvider": "spawn",
            },
        },
    ]
    return {
        profile_dir / "package.json": json.dumps(package, indent=2) + "\n",
        profile_dir / "cordis.patch.yml": (
            "# Generated by scripts/install_allinflash_profile.py.\n"
            "# The All in Flash bundle inserts this row; this profile layer owns its local runtime values.\n"
            "- id: allinflash\n"
            "  config:\n"
            f"    command: '{command}'\n"
            "    commandArgs: ['run', 'allinluna', '--adapter', 'deepseek-harness']\n"
            f"    db: '{(allinluna_root / 'runtime.db').as_posix()}'\n"
            f"    cwd: '{allinluna_root.as_posix()}'\n"
            "    timeoutMs: 30000\n"
            "    model: deepseek-v4-flash\n"
            "    subagentProvider: spawn\n"
        ),
        profile_dir / "pnpm-workspace.yaml": "packages:\n  - .\nnodeLinker: hoisted\nautoInstallPeers: false\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dsh-home",
        type=Path,
        default=Path(os.environ.get("DSH_HOME", Path.home() / ".dsh")),
        help="DSH home directory (default: DSH_HOME or ~/.dsh)",
    )
    parser.add_argument("--profile", default="allinflash")
    parser.add_argument("--allinluna-root", type=Path, default=ROOT)
    parser.add_argument("--force", action="store_true", help="replace an existing generated profile")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.profile.replace("-", "").isalnum() or not args.profile[0].isalnum():
        parser.error("profile must contain only letters, numbers, and hyphens and start alphanumeric")
    profile_dir = args.dsh_home.expanduser().resolve() / "profiles" / args.profile
    files = profile_files(profile_dir=profile_dir, allinluna_root=args.allinluna_root.expanduser().resolve())
    if profile_dir.exists() and not args.force:
        parser.error(f"profile already exists: {profile_dir}; re-run with --force to replace it")
    if args.dry_run:
        print(json.dumps({"profile_dir": str(profile_dir), "files": [str(path) for path in files]}, indent=2))
        return 0
    profile_dir.mkdir(parents=True, exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    print(profile_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
