from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from allinluna_runtime.adapters.host.base import (
    DEEPSEEK_HARNESS_CREATE_TASK_TOOL,
    HostAction,
)
ROOT = Path(__file__).resolve().parents[2]
PLUGIN = ROOT / "plugins" / "deepseek-harness"


def _profile_files(*, profile_dir: Path) -> dict[Path, str]:
    spec = importlib.util.spec_from_file_location(
        "install_allinflash_profile", ROOT / "scripts" / "install_allinflash_profile.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.profile_files(profile_dir=profile_dir, allinluna_root=ROOT)


def test_deepseek_harness_plugin_has_valid_node_module_metadata() -> None:
    package = json.loads((PLUGIN / "package.json").read_text(encoding="utf-8"))

    assert package["name"] == "@zenx0x/allinflash"
    assert package["version"] == "0.2.0"
    assert package["type"] == "module"
    assert package["bin"]["allinflash"] == "./cli.js"
    assert "deepseek-harness" in package["keywords"]
    assert package["repository"]["directory"] == "plugins/deepseek-harness"
    assert package["peerDependencies"]["@deepseek-ai/dsh-tools"] == "^0.1.0-rc.6"


def test_deepseek_harness_plugin_parses_in_node() -> None:
    for source in ("index.js", "cli.js"):
        result = subprocess.run(
            ["node", "--check", str(PLUGIN / source)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
        )

        assert result.returncode == 0, f"{source}: {result.stderr}"


def test_allinflash_cli_initializes_an_idempotent_dedicated_profile(tmp_path: Path) -> None:
    dsh_home = tmp_path / "dsh-home"
    command = [
        "node", str(PLUGIN / "cli.js"), "init",
        "--dsh-home", str(dsh_home),
        "--skip-runtime-check",
        "--skip-install",
    ]
    first = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False, timeout=15)
    second = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False, timeout=15)

    assert first.returncode == 0, first.stderr
    assert second.returncode == 0, second.stderr
    payload = json.loads(second.stdout)
    profile = dsh_home / "profiles" / "allinflash"
    manifest = json.loads((profile / "package.json").read_text(encoding="utf-8"))
    patch = (profile / "cordis.patch.yml").read_text(encoding="utf-8")
    assert payload["start"] == "dsh --profile allinflash"
    assert manifest["dependencies"]["@zenx0x/allinflash"] == "0.2.0"
    assert manifest["dsh"]["profile"]["bundles"].count("@zenx0x/allinflash") == 1
    assert manifest["allinflash"] == {"managed": True, "version": "0.2.0"}
    assert patch.startswith("# Generated by @zenx0x/allinflash.")
    assert "command: 'allinluna'" in patch
    assert "commandArgs: ['--adapter', 'deepseek-harness']" in patch


def test_allinflash_cli_preserves_an_unmanaged_profile_without_force(tmp_path: Path) -> None:
    profile = tmp_path / "dsh-home" / "profiles" / "shared"
    profile.mkdir(parents=True)
    (profile / "package.json").write_text('{"name":"shared","private":true}\n', encoding="utf-8")
    (profile / "cordis.patch.yml").write_text("- id: existing\n", encoding="utf-8")
    result = subprocess.run(
        [
            "node", str(PLUGIN / "cli.js"), "init",
            "--dsh-home", str(tmp_path / "dsh-home"), "--profile", "shared",
            "--skip-runtime-check", "--skip-install",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        timeout=15,
    )

    assert result.returncode != 0
    assert "is not managed by All in Flash" in result.stderr
    assert (profile / "cordis.patch.yml").read_text(encoding="utf-8") == "- id: existing\n"


def test_allinflash_cli_fails_before_writing_when_runtime_is_missing(tmp_path: Path) -> None:
    dsh_home = tmp_path / "dsh-home"
    result = subprocess.run(
        [
            "node", str(PLUGIN / "cli.js"), "init",
            "--dsh-home", str(dsh_home),
            "--runtime-command", "allinluna-command-that-does-not-exist",
            "--skip-install",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        timeout=15,
    )

    assert result.returncode != 0
    assert "python -m pip install allinluna" in result.stderr
    assert not (dsh_home / "profiles" / "allinflash").exists()


def test_allinflash_profile_contains_the_exact_plugin_and_runtime_command(tmp_path: Path) -> None:
    files = _profile_files(profile_dir=tmp_path / "profiles" / "allinflash")
    package = json.loads(next(content for path, content in files.items() if path.name == "package.json"))
    patch = next(content for path, content in files.items() if path.name == "cordis.patch.yml")

    assert package["dependencies"]["@zenx0x/allinflash"].startswith("file:")
    assert package["dsh"]["profile"]["bundles"] == [
        "@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app", "@zenx0x/allinflash"
    ]
    assert "- id: allinflash" in patch
    assert "commandArgs: ['run', 'allinluna', '--adapter', 'deepseek-harness']" in patch


def test_deepseek_harness_plugin_is_a_dsh_bundle() -> None:
    package = json.loads((PLUGIN / "package.json").read_text(encoding="utf-8"))

    assert package["dsh"]["bundle"]["patch"] == "./cordis.patch.yml"


def test_deepseek_harness_top_level_action_keeps_its_exact_opcode() -> None:
    action = HostAction(
        action_id="action-allinflash",
        kind="create-top-level-task",
        idempotency_key="intent:allinflash",
        tool=DEEPSEEK_HARNESS_CREATE_TASK_TOOL,
        arguments={"target": {"type": "project"}, "prompt": "lane bootstrap", "model": "deepseek-v4-flash", "title": "Lane"},
        execution_class="top_level_task",
        tool_policy={"exact_tool": DEEPSEEK_HARNESS_CREATE_TASK_TOOL, "substitutions": [], "on_unavailable": "block"},
        host_capability_required=DEEPSEEK_HARNESS_CREATE_TASK_TOOL,
    )

    assert action.tool == DEEPSEEK_HARNESS_CREATE_TASK_TOOL
    assert action.tool_policy["exact_tool"] == DEEPSEEK_HARNESS_CREATE_TASK_TOOL


def test_cli_deepseek_harness_adapter_emits_the_allinflash_opcode() -> None:
    with tempfile.TemporaryDirectory() as directory:
        database = Path(directory) / "runtime.db"
        result = subprocess.run(
            [
                sys.executable, "-m", "allinluna_runtime.cli",
                "--adapter", "deepseek-harness", "--db", str(database),
                "start", "--goal", "verify allinflash adapter", "--model", "deepseek-v4-flash",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    actions = payload["actions"]
    assert actions
    assert actions[0]["tool"] == DEEPSEEK_HARNESS_CREATE_TASK_TOOL
    assert actions[0]["host_capability_required"] == DEEPSEEK_HARNESS_CREATE_TASK_TOOL


def test_cli_deepseek_harness_adapter_ingests_an_exact_child_receipt() -> None:
    with tempfile.TemporaryDirectory() as directory:
        database = Path(directory) / "runtime.db"
        start = subprocess.run(
            [
                sys.executable, "-m", "allinluna_runtime.cli",
                "--adapter", "deepseek-harness", "--db", str(database),
                "start", "--goal", "verify All in Flash child receipt", "--model", "deepseek-v4-flash",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
        assert start.returncode == 0, start.stderr
        start_payload = json.loads(start.stdout)
        action = start_payload["actions"][0]
        receipt = {
            "receipt_id": f"allinflash-receipt-{action['action_id']}",
            "status": "ready",
            "source": "deepseek-harness",
            "host_adapter": "deepseek-harness",
            "host_id": "allinflash-dsh",
            "thread_id": "dsh-child-test",
            "action_id": action["action_id"],
            "action_kind": action["kind"],
            "idempotency_key": action["idempotency_key"],
            "dispatch_key": action["idempotency_key"],
            "dispatch_id": action["dispatch_id"],
            "task_id": action["task_id"],
            "actual": True,
            "actual_tool": DEEPSEEK_HARNESS_CREATE_TASK_TOOL,
            "actual_capability": DEEPSEEK_HARNESS_CREATE_TASK_TOOL,
            "action_contract_hash": action["action_contract_hash"],
            "payload": {"provider": "spawn", "child_id": "dsh-child-test"},
        }
        run_id = start_payload["run_ref"].removeprefix("run://")
        ingest = subprocess.run(
            [
                sys.executable, "-m", "allinluna_runtime.cli",
                "--adapter", "deepseek-harness", "--db", str(database),
                "ingest-receipt", run_id, json.dumps(receipt),
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )

    assert ingest.returncode == 0, ingest.stderr
    result = json.loads(ingest.stdout)
    assert result["receipt"]["thread_id"] == "dsh-child-test"
    assert result["receipt"]["actual_tool"] == DEEPSEEK_HARNESS_CREATE_TASK_TOOL
